version: 2


jobs:
        
        orbs:
                 node: circleci/node@3.0.0
        #build:
                #docker:
        steps:
                - checkout
        # Download and cache dependencies
                - restore_cache:
                        keys: 
                        - v1-dependencies-{{ checksum "package.json" }}
                        - v1-dependencies-
                - run: npm install

                - save_cache:
                        paths:
                                - node_modules
                        key: v1-dependencies-{{ checksum "package.json" }}
                
                - run: npm test
deploy:
        orbs:
                 node: circleci/node@3.0.0
        steps:
                - checkout
                - run: npm install   

